name: CI

on: [push, pull_request ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]
        node-version: [ 14.x, 15.x ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup MySQL 8.0
        uses: ankane/setup-mysql@v1
        with:
          mysql-version: 8.0
          database: devstoa

      - name: Config MySQL
        run: |
          mysqladmin -u root password '12345678'
          exit;

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
          echo 'everything is done'
        env:
          CI: true
          